import { DataTable } from 'primereact/datatable';
import { FilterMatchMode, FilterOperator } from 'primereact/api';
import { Column } from 'primereact/column';
import { MdOutlineKeyboardArrowRight } from 'react-icons/md'
import './DataTable.css'
import CampoTexto from '@components/CampoTexto';
import Container from '@components/Container';
import BotaoGrupo from '@components/BotaoGrupo';
import Frame from '@components/Frame';
import Botao from '@components/Botao';
import { useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { FaPlusCircle } from 'react-icons/fa';
import ModalFerias from '../ModalFerias';
import { useSessaoUsuarioContext } from '../../contexts/SessaoUsuario';
import { GrAddCircle } from 'react-icons/gr';

function formatarDataBr(data) {
    const [ano, mes, dia] = data.split('-');
    return `${dia}/${mes}/${ano}`;
}

const fakeData = [
    {
        id: 1,
        colaborador_id: 8,
        data_inicio: formatarDataBr("2025-02-01"),
        data_fim: formatarDataBr("2025-02-10"),
        data_inicio_aquisicao: formatarDataBr("2024-02-01"),
        data_fim_aquisicao: formatarDataBr("2024-02-10"),
        dias: 10,
        "13": "Sim",
        abono: "6"
    },
    {
        id: 2,
        colaborador_id: 11,
        data_inicio: formatarDataBr("2025-03-05"),
        data_fim: formatarDataBr("2025-03-15"),
        data_inicio_aquisicao: formatarDataBr("2024-03-05"),
        data_fim_aquisicao: formatarDataBr("2024-03-15"),
        dias: 11,
        "13": "Não",
        abono: "5"
    },
    {
        id: 3,
        colaborador_id: 12,
        data_inicio: formatarDataBr("2025-04-10"),
        data_fim: formatarDataBr("2025-04-20"),
        data_inicio_aquisicao: formatarDataBr("2024-04-10"),
        data_fim_aquisicao: formatarDataBr("2024-04-20"),
        dias: 11,
        "13": "Sim",
        abono: "10"
    },
    {
        id: 4,
        colaborador_id: 13,
        data_inicio: formatarDataBr("2025-05-01"),
        data_fim: formatarDataBr("2025-05-10"),
        data_inicio_aquisicao: formatarDataBr("2024-05-01"),
        data_fim_aquisicao: formatarDataBr("2024-05-10"),
        dias: 10,
        "13": "Sim",
        abono: "5"
    },
    {
        id: 5,
        colaborador_id: 8,
        data_inicio: formatarDataBr("2025-06-15"),
        data_fim: formatarDataBr("2025-06-25"),
        data_inicio_aquisicao: formatarDataBr("2024-06-15"),
        data_fim_aquisicao: formatarDataBr("2024-06-25"),
        dias: 11,
        "13": "Não",
        abono: "5"
    },
    {
        id: 6,
        colaborador_id: 11,
        data_inicio: formatarDataBr("2025-07-01"),
        data_fim: formatarDataBr("2025-07-10"),
        data_inicio_aquisicao: formatarDataBr("2024-07-01"),
        data_fim_aquisicao: formatarDataBr("2024-07-10"),
        dias: 10,
        "13": "Sim",
        abono: "10"
    }
];

const colaboradores = [
    {
        "id": 8,
        "dados_pessoa_fisica": {
            "id": 8,
            "created_at": "2024-11-04T19:05:01.679224-03:00",
            "updated_at": "2024-11-04T19:05:01.694880-03:00",
            "nome": "JOSÉ DOS SANTOS VIEIRA",
            "data_nascimento": "1994-02-19",
            "estado_natal": null,
            "naturalidade": null,
            "apelido": "GUILHERME",
            "estado_civil": null,
            "sexo": "M",
            "nacionalidade": null,
            "rua": null,
            "numero": null,
            "complemento": null,
            "bairro": null,
            "estado": null,
            "cidade": null,
            "cep": null,
            "pais": null,
            "cpf": "37831216049",
            "email": null,
            "registro_profissional": null,
            "imagem_id": null,
            "telefone1": "999999999",
            "telefone2": null,
            "identidade": null,
            "uf_identidade": null,
            "orgao_emissor_ident": null,
            "data_emissao_ident": null,
            "titulo_eleitor": null,
            "zona_titulo_eleitor": null,
            "secao_titulo_eleitor": null,
            "carteira_trabalho": null,
            "serie_carteira_trab": null,
            "uf_carteira_trab": null,
            "data_emissao_ctps": null,
            "nit": null,
            "carteira_motorista": null,
            "tipo_carteira_habilit": null,
            "data_venc_habilit": null,
            "certificado_reservista": null,
            "naturalizado": false,
            "data_venc_ctps": null,
            "tipo_visto": null,
            "email_pessoal": "",
            "cor_raca": null,
            "deficiente_fisico": false,
            "telefone3": null,
            "numero_passaporte": null,
            "pais_origem": null,
            "data_emissao_passaporte": null,
            "data_validade_passaporte": null,
            "observacoes_pessoa": "",
            "codigo_municipio": null,
            "circunscricao_militar": "",
            "orgao_expedicao": "",
            "regiao_militar": "",
            "situacao_militar": "",
            "data_titulo_eleitor": null,
            "estado_emissor_tit_eleitor": "",
            "tipo_sanguineo": null,
            "id_biometria": null,
            "imagem": null,
            "primeiro_nome": "",
            "sobrenome_pai": "",
            "sobrenome_mae": "",
            "uf_registro_profissional": "",
            "data_emissao_cnh": null,
            "data_naturalizacao": null,
            "id_pais": null,
            "nome_social": "TESTE FMV"
        },
        "dependentes": [],
        "created_at": "2024-11-04T19:05:01.694880-03:00",
        "updated_at": "2024-11-04T19:05:01.694880-03:00",
        "chapa": "01709",
        "codigo_ficha_registro": null,
        "situacao": "A",
        "dt_situacao": null,
        "tipo_admissao": null,
        "dt_admissao": "2018-09-11",
        "tipo_demissao": null,
        "dt_demissao": null,
        "dt_transferencia": null,
        "departamento": "GERAL",
        "id_secao": null,
        "salario": "1488.30",
        "codigo_jornada": "044",
        "agencia": null,
        "conta_corrente": null,
        "pix": "",
        "status_beneficios": null,
        "id_pessoafisica": 8,
        "centro_custo": null,
        "filial": 1,
        "id_funcao": 43,
        "banco": null
    },
    {
        "id": 11,
        "dados_pessoa_fisica": {
            "id": 11,
            "created_at": "2024-11-04T19:05:01.710920-03:00",
            "updated_at": "2024-11-04T19:05:01.710920-03:00",
            "nome": "AGNALDO TIMOTEO",
            "data_nascimento": "1975-12-21",
            "estado_natal": null,
            "naturalidade": null,
            "apelido": "AGNALDO",
            "estado_civil": null,
            "sexo": "M",
            "nacionalidade": null,
            "rua": null,
            "numero": null,
            "complemento": null,
            "bairro": null,
            "estado": null,
            "cidade": null,
            "cep": null,
            "pais": null,
            "cpf": "16693058302",
            "email": null,
            "registro_profissional": null,
            "imagem_id": null,
            "telefone1": "999999999",
            "telefone2": null,
            "identidade": null,
            "uf_identidade": null,
            "orgao_emissor_ident": null,
            "data_emissao_ident": null,
            "titulo_eleitor": null,
            "zona_titulo_eleitor": null,
            "secao_titulo_eleitor": null,
            "carteira_trabalho": null,
            "serie_carteira_trab": null,
            "uf_carteira_trab": null,
            "data_emissao_ctps": null,
            "nit": null,
            "carteira_motorista": null,
            "tipo_carteira_habilit": null,
            "data_venc_habilit": null,
            "certificado_reservista": null,
            "naturalizado": false,
            "data_venc_ctps": null,
            "tipo_visto": null,
            "email_pessoal": "",
            "cor_raca": null,
            "deficiente_fisico": false,
            "telefone3": null,
            "numero_passaporte": null,
            "pais_origem": null,
            "data_emissao_passaporte": null,
            "data_validade_passaporte": null,
            "observacoes_pessoa": "",
            "codigo_municipio": null,
            "circunscricao_militar": "",
            "orgao_expedicao": "",
            "regiao_militar": "",
            "situacao_militar": "",
            "data_titulo_eleitor": null,
            "estado_emissor_tit_eleitor": "",
            "tipo_sanguineo": null,
            "id_biometria": null,
            "imagem": null,
            "primeiro_nome": "",
            "sobrenome_pai": "",
            "sobrenome_mae": "",
            "uf_registro_profissional": "",
            "data_emissao_cnh": null,
            "data_naturalizacao": null,
            "id_pais": null,
            "nome_social": "TESTE FMV"
        },
        "dependentes": [],
        "created_at": "2024-11-04T19:05:01.710920-03:00",
        "updated_at": "2024-11-04T19:05:01.710920-03:00",
        "chapa": "01736",
        "codigo_ficha_registro": null,
        "situacao": "A",
        "dt_situacao": null,
        "tipo_admissao": null,
        "dt_admissao": "2018-12-01",
        "tipo_demissao": null,
        "dt_demissao": null,
        "dt_transferencia": null,
        "departamento": "GERAL",
        "id_secao": null,
        "salario": "1320.00",
        "codigo_jornada": "001",
        "agencia": null,
        "conta_corrente": null,
        "pix": "",
        "status_beneficios": null,
        "id_pessoafisica": 11,
        "centro_custo": null,
        "filial": 1,
        "id_funcao": 1,
        "banco": null
    },
    {
        "id": 12,
        "dados_pessoa_fisica": {
            "id": 12,
            "created_at": "2024-11-04T19:05:01.710920-03:00",
            "updated_at": "2024-11-04T19:05:01.710920-03:00",
            "nome": "ALCEU VALENCA",
            "data_nascimento": "1981-12-05",
            "estado_natal": null,
            "naturalidade": null,
            "apelido": "ALCEU",
            "estado_civil": null,
            "sexo": "M",
            "nacionalidade": null,
            "rua": null,
            "numero": null,
            "complemento": null,
            "bairro": null,
            "estado": null,
            "cidade": null,
            "cep": null,
            "pais": null,
            "cpf": "96986583869",
            "email": null,
            "registro_profissional": null,
            "imagem_id": null,
            "telefone1": "999999999",
            "telefone2": null,
            "identidade": null,
            "uf_identidade": null,
            "orgao_emissor_ident": null,
            "data_emissao_ident": null,
            "titulo_eleitor": null,
            "zona_titulo_eleitor": null,
            "secao_titulo_eleitor": null,
            "carteira_trabalho": null,
            "serie_carteira_trab": null,
            "uf_carteira_trab": null,
            "data_emissao_ctps": null,
            "nit": null,
            "carteira_motorista": null,
            "tipo_carteira_habilit": null,
            "data_venc_habilit": null,
            "certificado_reservista": null,
            "naturalizado": false,
            "data_venc_ctps": null,
            "tipo_visto": null,
            "email_pessoal": "",
            "cor_raca": null,
            "deficiente_fisico": false,
            "telefone3": null,
            "numero_passaporte": null,
            "pais_origem": null,
            "data_emissao_passaporte": null,
            "data_validade_passaporte": null,
            "observacoes_pessoa": "",
            "codigo_municipio": null,
            "circunscricao_militar": "",
            "orgao_expedicao": "",
            "regiao_militar": "",
            "situacao_militar": "",
            "data_titulo_eleitor": null,
            "estado_emissor_tit_eleitor": "",
            "tipo_sanguineo": null,
            "id_biometria": null,
            "imagem": null,
            "primeiro_nome": "",
            "sobrenome_pai": "",
            "sobrenome_mae": "",
            "uf_registro_profissional": "",
            "data_emissao_cnh": null,
            "data_naturalizacao": null,
            "id_pais": null,
            "nome_social": "TESTE FMV"
        },
        "dependentes": [],
        "created_at": "2024-11-04T19:05:01.710920-03:00",
        "updated_at": "2024-11-04T19:05:01.710920-03:00",
        "chapa": "01786",
        "codigo_ficha_registro": null,
        "situacao": "A",
        "dt_situacao": null,
        "tipo_admissao": null,
        "dt_admissao": "2018-11-22",
        "tipo_demissao": null,
        "dt_demissao": null,
        "dt_transferencia": null,
        "departamento": "GERAL",
        "id_secao": null,
        "salario": "5000.00",
        "codigo_jornada": "032",
        "agencia": null,
        "conta_corrente": null,
        "pix": "",
        "status_beneficios": null,
        "id_pessoafisica": 12,
        "centro_custo": null,
        "filial": 1,
        "id_funcao": 1,
        "banco": null
    },
    {
        "id": 13,
        "dados_pessoa_fisica": {
            "id": 13,
            "created_at": "2024-11-04T19:05:01.726573-03:00",
            "updated_at": "2024-11-04T19:05:01.726573-03:00",
            "nome": "MILTON NASCIMENTO",
            "data_nascimento": "2000-01-01",
            "estado_natal": null,
            "naturalidade": null,
            "apelido": "MILTON",
            "estado_civil": null,
            "sexo": "M",
            "nacionalidade": null,
            "rua": null,
            "numero": null,
            "complemento": null,
            "bairro": null,
            "estado": null,
            "cidade": null,
            "cep": null,
            "pais": null,
            "cpf": "17107247492",
            "email": null,
            "registro_profissional": null,
            "imagem_id": null,
            "telefone1": "999999999",
            "telefone2": null,
            "identidade": null,
            "uf_identidade": null,
            "orgao_emissor_ident": null,
            "data_emissao_ident": null,
            "titulo_eleitor": null,
            "zona_titulo_eleitor": null,
            "secao_titulo_eleitor": null,
            "carteira_trabalho": null,
            "serie_carteira_trab": null,
            "uf_carteira_trab": null,
            "data_emissao_ctps": null,
            "nit": null,
            "carteira_motorista": null,
            "tipo_carteira_habilit": null,
            "data_venc_habilit": null,
            "certificado_reservista": null,
            "naturalizado": false,
            "data_venc_ctps": null,
            "tipo_visto": null,
            "email_pessoal": "",
            "cor_raca": null,
            "deficiente_fisico": false,
            "telefone3": null,
            "numero_passaporte": null,
            "pais_origem": null,
            "data_emissao_passaporte": null,
            "data_validade_passaporte": null,
            "observacoes_pessoa": "",
            "codigo_municipio": null,
            "circunscricao_militar": "",
            "orgao_expedicao": "",
            "regiao_militar": "",
            "situacao_militar": "",
            "data_titulo_eleitor": null,
            "estado_emissor_tit_eleitor": "",
            "tipo_sanguineo": null,
            "id_biometria": null,
            "imagem": null,
            "primeiro_nome": "",
            "sobrenome_pai": "",
            "sobrenome_mae": "",
            "uf_registro_profissional": "",
            "data_emissao_cnh": null,
            "data_naturalizacao": null,
            "id_pais": null,
            "nome_social": "TESTE FMV"
        },
        "dependentes": [
            {
                "id": 1,
                "dados_pessoa_fisica": {
                    "id": 7,
                    "created_at": "2024-11-04T19:05:01.679224-03:00",
                    "updated_at": "2024-11-04T19:05:01.679224-03:00",
                    "nome": "KASSIA ELLER",
                    "data_nascimento": "1996-01-09",
                    "estado_natal": null,
                    "naturalidade": null,
                    "apelido": "KASSIA",
                    "estado_civil": null,
                    "sexo": "F",
                    "nacionalidade": null,
                    "rua": null,
                    "numero": null,
                    "complemento": null,
                    "bairro": null,
                    "estado": null,
                    "cidade": null,
                    "cep": null,
                    "pais": null,
                    "cpf": "66290298445",
                    "email": null,
                    "registro_profissional": null,
                    "imagem_id": null,
                    "telefone1": "999999999",
                    "telefone2": null,
                    "identidade": null,
                    "uf_identidade": null,
                    "orgao_emissor_ident": null,
                    "data_emissao_ident": null,
                    "titulo_eleitor": null,
                    "zona_titulo_eleitor": null,
                    "secao_titulo_eleitor": null,
                    "carteira_trabalho": null,
                    "serie_carteira_trab": null,
                    "uf_carteira_trab": null,
                    "data_emissao_ctps": null,
                    "nit": null,
                    "carteira_motorista": null,
                    "tipo_carteira_habilit": null,
                    "data_venc_habilit": null,
                    "certificado_reservista": null,
                    "naturalizado": false,
                    "data_venc_ctps": null,
                    "tipo_visto": null,
                    "email_pessoal": "",
                    "cor_raca": null,
                    "deficiente_fisico": false,
                    "telefone3": null,
                    "numero_passaporte": null,
                    "pais_origem": null,
                    "data_emissao_passaporte": null,
                    "data_validade_passaporte": null,
                    "observacoes_pessoa": "",
                    "codigo_municipio": null,
                    "circunscricao_militar": "",
                    "orgao_expedicao": "",
                    "regiao_militar": "",
                    "situacao_militar": "",
                    "data_titulo_eleitor": null,
                    "estado_emissor_tit_eleitor": "",
                    "tipo_sanguineo": null,
                    "id_biometria": null,
                    "imagem": null,
                    "primeiro_nome": "",
                    "sobrenome_pai": "",
                    "sobrenome_mae": "",
                    "uf_registro_profissional": "",
                    "data_emissao_cnh": null,
                    "data_naturalizacao": null,
                    "id_pais": null,
                    "nome_social": "TESTE FMV"
                },
                "created_at": "2024-12-23T11:18:00.263816-03:00",
                "updated_at": "2024-12-23T11:18:00.263816-03:00",
                "grau_parentesco": "1",
                "id_funcionario": 13,
                "id_pessoafisica": 7
            },
            {
                "id": 2,
                "dados_pessoa_fisica": {
                    "id": 95,
                    "created_at": "2024-11-04T19:05:02.282505-03:00",
                    "updated_at": "2024-11-04T19:05:02.282505-03:00",
                    "nome": "RONALDO FAVERO",
                    "data_nascimento": "1986-02-09",
                    "estado_natal": null,
                    "naturalidade": null,
                    "apelido": "RONALDO",
                    "estado_civil": null,
                    "sexo": "M",
                    "nacionalidade": null,
                    "rua": null,
                    "numero": null,
                    "complemento": null,
                    "bairro": null,
                    "estado": null,
                    "cidade": null,
                    "cep": null,
                    "pais": null,
                    "cpf": "93709414369",
                    "email": null,
                    "registro_profissional": null,
                    "imagem_id": null,
                    "telefone1": "999999999",
                    "telefone2": null,
                    "identidade": null,
                    "uf_identidade": null,
                    "orgao_emissor_ident": null,
                    "data_emissao_ident": null,
                    "titulo_eleitor": null,
                    "zona_titulo_eleitor": null,
                    "secao_titulo_eleitor": null,
                    "carteira_trabalho": null,
                    "serie_carteira_trab": null,
                    "uf_carteira_trab": null,
                    "data_emissao_ctps": null,
                    "nit": null,
                    "carteira_motorista": null,
                    "tipo_carteira_habilit": null,
                    "data_venc_habilit": null,
                    "certificado_reservista": null,
                    "naturalizado": false,
                    "data_venc_ctps": null,
                    "tipo_visto": null,
                    "email_pessoal": "",
                    "cor_raca": null,
                    "deficiente_fisico": false,
                    "telefone3": null,
                    "numero_passaporte": null,
                    "pais_origem": null,
                    "data_emissao_passaporte": null,
                    "data_validade_passaporte": null,
                    "observacoes_pessoa": "",
                    "codigo_municipio": null,
                    "circunscricao_militar": "",
                    "orgao_expedicao": "",
                    "regiao_militar": "",
                    "situacao_militar": "",
                    "data_titulo_eleitor": null,
                    "estado_emissor_tit_eleitor": "",
                    "tipo_sanguineo": null,
                    "id_biometria": null,
                    "imagem": null,
                    "primeiro_nome": "",
                    "sobrenome_pai": "",
                    "sobrenome_mae": "",
                    "uf_registro_profissional": "",
                    "data_emissao_cnh": null,
                    "data_naturalizacao": null,
                    "id_pais": null,
                    "nome_social": "TESTE FMV"
                },
                "created_at": "2025-02-01T15:35:47.998839-03:00",
                "updated_at": "2025-02-01T15:35:47.998839-03:00",
                "grau_parentesco": "Filho",
                "id_funcionario": 13,
                "id_pessoafisica": 95
            }
        ],
        "created_at": "2024-11-04T19:05:01.726573-03:00",
        "updated_at": "2024-11-04T19:05:01.726573-03:00",
        "chapa": "01787",
        "codigo_ficha_registro": null,
        "situacao": "A",
        "dt_situacao": null,
        "tipo_admissao": null,
        "dt_admissao": "2019-08-01",
        "tipo_demissao": null,
        "dt_demissao": null,
        "dt_transferencia": null,
        "departamento": "GERAL",
        "id_secao": null,
        "salario": "5000.00",
        "codigo_jornada": "001",
        "agencia": null,
        "conta_corrente": null,
        "pix": "",
        "status_beneficios": null,
        "id_pessoafisica": 13,
        "centro_custo": null,
        "filial": 1,
        "id_funcao": 4,
        "banco": null
    }
];

function DataTableFerias({ ferias, colaborador = null }) {
    const [selectedFerias, setSelectedFerias] = useState(0);
    const [modalOpened, setModalOpened] = useState(false);
    const [globalFilterValue, setGlobalFilterValue] = useState('');
    const [filters, setFilters] = useState({
        global: { value: null, matchMode: FilterMatchMode.CONTAINS },
    });
    const navegar = useNavigate();
    const { usuario } = useSessaoUsuarioContext();

    const onGlobalFilterChange = (value) => {
        let _filters = { ...filters };
        _filters['global'].value = value;
        setFilters(_filters);
        setGlobalFilterValue(value);
    };

    function verDetalhes(value) {
        setSelectedFerias(value.id);
    }

    function formataCPF(cpf) {
        cpf = cpf.replace(/[^\d]/g, "");
        return cpf.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, "$1.$2.$3-$4");
    }

    const representativeColaboradorTemplate = (rowData) => {
        
        const colab = colaboradores.filter(collaborator => collaborator.id == rowData.colaborador_id);
        if(colab.length > 0)
        {
            return (
                <b>{colab[0]?.dados_pessoa_fisica?.nome}</b>
            )
        }
        else
        {
            return ""
        }
    }
    

    // Filtra os dados com base no colaborador, se fornecido
    const filteredData = colaborador ? fakeData.filter(feria => feria.colaborador_id == colaborador) : fakeData;

    return (
        <>
            <Frame alinhamento="center" gap="20px">
                <DataTable value={filteredData} filters={filters} globalFilterFields={[]} emptyMessage="Não foram encontrados férias registradas" selection={selectedFerias} onSelectionChange={(e) => verDetalhes(e.value)} selectionMode="single" paginator rows={6} tableStyle={{ minWidth: '68vw' }}>
                    {!colaborador && <Column body={representativeColaboradorTemplate} field="colaborador_id" header="Colaborador" style={{ width: '15%' }}></Column>}
                    <Column field="data_inicio_aquisicao" header="Data Inicio Aquisição" style={{ width: '15%' }}></Column>
                    <Column field="data_fim_aquisicao" header="Data Fim Aquisição" style={{ width: '15%' }}></Column>
                    <Column field="data_inicio" header="Data Início" style={{ width: '15%' }}></Column>
                    <Column field="data_fim" header="Data Fim" style={{ width: '15%' }}></Column>
                    <Column field="dias" header="Dias de Férias" style={{ width: '15%' }}></Column>
                    <Column field="13" header="13º" style={{ width: '15%' }}></Column>
                    <Column field="abono" header="Dias de Abono" style={{ width: '15%' }}></Column>
                </DataTable>
                <ModalFerias opened={modalOpened} aoFechar={() => setModalOpened(false)} />
            </Frame>
        </>
    )
}

export default DataTableFerias;